// <auto-generated />
namespace ne_izlesek_Web_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Veritabani2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Veritabani2));
        
        string IMigrationMetadata.Id
        {
            get { return "202311121531245_Veritabani2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
